name: Build and deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies and build
      run: |
        yarn install
        yarn build
    - name: deploy dist to gh-pages
      run: |
        git config --global user.name 'Chris Svajlenka'
        git config --global user.email 'chris@svajlenka.com'
        git push origin `git subtree split --prefix dist main`:gh-pages --force